title: Yuqing Yang
logo: /image/Myself-Circle.png
theme: jekyll-theme-minimal
location         : "San Francisco, CA"
github           : "https://github.com/yyuqing-42"
linkedin         : "https://www.linkedin.com/in/yyuqing/"
